name: ecommerce_zarinpal
description: A new Flutter project.


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^7.3.0
  zarinpal: ^1.0.4+1
  iconly: ^1.0.1
  transparent_image: ^2.0.0
  solid_bottom_sheet: ^0.1.10
  uni_links: ^0.5.1
  url_launcher: ^6.0.12
  lottie: ^1.2.1
  equatable: ^2.0.3
  flutter_spinkit: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:


  uses-material-design: true

  # assets:
    # - assets/

  fonts:
    - family: Shabnam
      fonts:
        - asset: assets/fonts/Shabnam-FD.ttf
          weight: 300
        - asset: assets/fonts/Shabnam-Medium-FD.ttf
          weight: 600
        - asset: assets/fonts/Shabnam-Bold-FD.ttf
          weight: 900
